name: Deploy to EC2
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    - name: Build and push Docker image
      run: |
        docker build -t maulanadsgn/node-example-cicd:${{ env.SHORT_SHA }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push maulanadsgn/node-example-cicd:${{ env.SHORT_SHA }}
    outputs:
      SHORT_SHA: ${{ env.SHORT_SHA }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull maulanadsgn/node-example-cicd:${{ needs.build.outputs.SHORT_SHA }}
          docker stop node-example || true
          docker rm node-example || true
          docker run -d -p 3000:3000 --name node-example maulanadsgn/node-example-cicd:${{ needs.build.outputs.SHORT_SHA }}