name: Deploy to EC2
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create short SHA
      run: echo ::set-env name=SHORT_SHA::$(echo $GITHUB_SHA | cut -c1-7)
    - name: Build and push Docker image
      run: |
        docker build -t node-example-cicd:${{ env.SHORT_SHA }} .
        docker tag node-example-cicd:${{ env.SHORT_SHA }} maulanadsgn/node-example-cicd:latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push maulanadsgn/node-example-cicd:${{ env.SHORT_SHA }}